### ISSUE TITLE
Documentation outdated

### ISSUE THREAD

**Issue by acka47** [rudof-project/rudof#145]
Hi, I have just installed rudof (which worked without any problems) and then wanted to try it with some Shacl validation. However, the information in the README seems to be outdated:

https://github.com/rudof-project/rudof/blob/6d7815e92ba5a41f79e60ba482bbc6a701b249bc/README.md?plain=1#L91

The line contains the option `--data` which – if used –gives back an error :

```
$ rudof shacl-validate --shapes examples/simple_shacl.ttl --data examples/simple.ttl
error: unexpected argument '--data' found

  tip: a similar argument exists: '--data-format'
```

Apparently the `--data/-d` option was removed at some point and you should instead use this:

```
$ rudof shacl-validate --shapes examples/simple_shacl.ttl examples/simple.ttl
Result:
Validation Report: [
	conforms: true,
	result:
]
``

**Comment by labra** [comment]
Thanks for the PR
