### ISSUE TITLE
Action that publishes python bindings seems to fail...

### ISSUE THREAD

**Issue by labra** [rudof-project/rudof#151]
According to this: https://github.com/rudof-project/rudof/actions/runs/10772107607

**Comment by seakayone** [comment]
I checked the logs and https://github.com/openssl/openssl/issues/25366 seems to be causing it"
```
   --- stderr
  "pairs" is not exported by the List::Util module
  Can't continue after import errors at util/mkinstallvars.pl line 14.
  BEGIN failed--compilation aborted at util/mkinstallvars.pl line 14.
  make: *** [builddata.pm] Error 255
  thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/openssl-src-300.3.2+3.3.2/src/lib.rs:633:9:
  ```
  
  This is the error message mentioned in above openssl issue. The linux build containers seem to have an older Perl version than expected.

**Comment by seakayone** [comment]
AFAIU https://github.com/openssl/openssl/pull/25367 replaces the missing Perl `pairs`, but this is not yet released.
