### ISSUE TITLE
v0.1.24 contains empty config file

### ISSUE THREAD

**Issue by jonassmedegaard** [rudof-project/rudof#155]
Rudof v0.1.24 contains the empty file `rudof_cli/config/default_data_config.yml` - since git tracks content, not files, that is problematic to handle for some distribution processes (including mine, for preparing packaging for Debian).

Please consider avoiding empty files, either by generating during build (and cleaning up again as needed), or adding comments to only be virtually empty.

**Comment by labra** [comment]
Thanks, the file was a leftover which is not necessary. I removed it and in principle, it shouldn't appear in the next release.

**Comment by labra** [comment]
I think the empty file has already been removed in release 0.1.25

**Comment by jonassmedegaard** [comment]
Yes. Thanks!
