### ISSUE TITLE
docs: enumeration should be two enumerations

### ISSUE THREAD

**Issue by jonassmedegaard** [rudof-project/rudof#193]
The file <docs/src/references/faq.md> contains this:

> The goal of `rudof` is to become a useful tool for RDF practitioners who want to either check the quality of their RDF data, convert RDF data or RDF data shapes.

I don't think you mean rudof is either of these three, enumerated above:

* check the quality of their RDF data
* convert RDF data
* RDF data shapes

...because the first two are functional desires of rudof whereas the third is not.

Instead, I think you mean either of these two:

* check the quality of their RDF data
* convert RDF data or RDF data shapes

I.e. an enumeration of two functional desires of rudof, where the second is an enumeration of two objects for conversion. That latter sentence is, I believe, instead phrased like this:

> The goal of `rudof` is to become a useful tool for RDF practitioners who want to either check the quality of their RDF data, or convert RDF data or RDF data shapes.

**Comment by labra** [comment]
Thanks, I think it is solved now.

By the way, I added your name as contributor, I hope it is OK for you as you are really contributing a lot to improve the quality of the project as well as the name 😄
