### ISSUE TITLE
Turtle parser does not handle relative URIs

### ISSUE THREAD

**Issue by jeswr** [rudof-project/rudof#226]
Running the following

```
./rudof convert -m shacl -x shex -s https://raw.githubusercontent.com/solid-contrib/catalog/refs/heads/main/catalog-shape.ttl -f turtle -o ./catalog.shex
```

where the first line of `catalog-shape.ttl` is

```
@prefix : <#> .
```

gives the error

```
Error: Read error: Parser error between at line 1 between columns 11 and column 14: No scheme found in an absolute IRI 
```

However, this is valid turtle and should parse.

**Comment by labra** [comment]
Indeed, the system requires relative IRIs to be resolved. 

At this moment, there is a way to resolve relative IRIs by specifying the `base` IRI which will be used in the resolution of relative IRIs. The specification can be done passing `rudof` a config file. For example, if you save the following content in a file called `shacl_config.yml`:

```yaml
rdf_data:
  base: http://example.org/
```

You can invoke rudof as:

```sh
./rudof convert -m shacl -x shex -s https://raw.githubusercontent.com/solid-contrib/catalog/refs/heads/main/catalog-shape.ttl -f turtle -o ./catalog.shex -c shacl_config.yml
```

And it should work.

**Comment by jeswr** [comment]
Got it, thanks for the pointer on how to configure.

I am still wondering why the base is not set automatically based on the URL that the document was returned from in this case.

**Comment by labra** [comment]
> I am still wondering why the base is not set automatically based on the URL that the document was returned from in this case.

Indeed, I think you are right, and we should probably change the default behaviour that complains about relative URIs to a behaviour that assumes the URL of the document by default which could be overriden by the configuration process if desired. I will add a new specific issue for that and if you agree, I could close this one.

**Comment by jeswr** [comment]
> I will add a new specific issue for that and if you agree, I could close this one.

Sounds good - thanks for opening the new issue!

**Comment by labra** [comment]
By the way, the release 0.1.59 supports relative URIs by default. However, when I tried with the initial example that you provided, the ShEx generated contains some spurious shapes that come from the strange use of `sh:targetClass` in an `sh:or`. I already commented it in a issue to that repository https://github.com/solid-contrib/catalog/issues/6
